import { Property, Agent } from './supabase'

export const mockAgents: Agent[] = [
    {
        id: '1',
        agent_id: 'mock-agent-001',
        name: 'Sarah Chen',
        phone: '+60123456789',
        email: 'sarah.chen@example.com',
        agency: 'Premier Properties',
        photo_url: null,
        whatsapp_link: 'https://api.whatsapp.com/send?phone=60123456789',
        profile_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        id: '2',
        agent_id: 'mock-agent-002',
        name: 'Marcus Tan',
        phone: '+60129876543',
        email: 'marcus.tan@example.com',
        agency: 'Elite Realty',
        photo_url: null,
        whatsapp_link: 'https://api.whatsapp.com/send?phone=60129876543',
        profile_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
    {
        id: '3',
        agent_id: 'mock-agent-003',
        name: 'Aisha Rahman',
        phone: '+60187654321',
        email: 'aisha.rahman@example.com',
        agency: 'Luxury Homes MY',
        photo_url: null,
        whatsapp_link: 'https://api.whatsapp.com/send?phone=60187654321',
        profile_url: null,
        created_at: '2024-01-01',
        updated_at: '2024-01-01',
    },
]

export const mockProperties: Property[] = [
    {
        id: '1',
        listing_id: 'mock-001',
        listing_url: 'https://www.propertyguru.com.my/property-listing/mock-001',
        agent_id: '1',
        property_name: 'Luxury Penthouse in KLCC',
        address: 'KLCC, Kuala Lumpur',
        state: 'Kuala Lumpur',
        price: 2500000,
        price_per_sqft: 781,
        bedrooms: 4,
        bathrooms: 3,
        size: '3,200 sqft',
        property_type: 'Condo',
        tenure: 'Freehold',
        built_year: '2018',
        listed_date: '1 Dec 2024',
        furnishing: 'Fully Furnished',
        description: 'Stunning penthouse with panoramic city views. Features include a private pool, modern kitchen, and premium finishes throughout.',
        facilities: { amenities: ['Swimming Pool', 'Gym', 'Parking'], common_facilities: ['24-hour Security', 'Lobby'] },
        images: ['property1.jpg'],
        image_count: 1,
        main_image_url: null,
        latitude: 3.1588, // KLCC area
        longitude: 101.7114,
        source: 'mock',
        scraped_at: '2024-12-01T00:00:00Z',
        created_at: '2024-12-01',
        updated_at: '2024-12-01',
    },
    {
        id: '2',
        listing_id: 'mock-002',
        listing_url: 'https://www.propertyguru.com.my/property-listing/mock-002',
        agent_id: '2',
        property_name: 'Modern Semi-D in Damansara Heights',
        address: 'Damansara Heights, Kuala Lumpur',
        state: 'Kuala Lumpur',
        price: 3800000,
        price_per_sqft: 844,
        bedrooms: 5,
        bathrooms: 4,
        size: '4,500 sqft',
        property_type: 'Landed',
        tenure: 'Freehold',
        built_year: '2015',
        listed_date: '2 Dec 2024',
        furnishing: 'Partially Furnished',
        description: 'Beautiful semi-detached house in prestigious neighborhood. Spacious layout with garden and covered parking.',
        facilities: { amenities: ['Garden', 'Parking'], common_facilities: ['Gated Community'] },
        images: ['property2.jpg'],
        image_count: 1,
        main_image_url: null,
        latitude: 3.1704, // Damansara Heights
        longitude: 101.6558,
        source: 'mock',
        scraped_at: '2024-12-02T00:00:00Z',
        created_at: '2024-12-02',
        updated_at: '2024-12-02',
    },
    {
        id: '3',
        listing_id: 'mock-003',
        listing_url: 'https://www.propertyguru.com.my/property-listing/mock-003',
        agent_id: '1',
        property_name: 'Cozy Apartment in Mont Kiara',
        address: 'Mont Kiara, Kuala Lumpur',
        state: 'Kuala Lumpur',
        price: 680000,
        price_per_sqft: 618,
        bedrooms: 2,
        bathrooms: 2,
        size: '1,100 sqft',
        property_type: 'Apartment',
        tenure: 'Freehold',
        built_year: '2012',
        listed_date: '3 Dec 2024',
        furnishing: 'Fully Furnished',
        description: 'Well-maintained apartment perfect for young professionals. Close to amenities and public transport.',
        facilities: { amenities: ['Swimming Pool', 'Gym'], common_facilities: ['Parking'] },
        images: ['property3.jpg'],
        image_count: 1,
        main_image_url: null,
        latitude: 3.1725, // Mont Kiara
        longitude: 101.6506,
        source: 'mock',
        scraped_at: '2024-12-03T00:00:00Z',
        created_at: '2024-12-03',
        updated_at: '2024-12-03',
    },
    {
        id: '4',
        listing_id: 'mock-004',
        listing_url: 'https://www.propertyguru.com.my/property-listing/mock-004',
        agent_id: '3',
        property_name: 'Commercial Office Space in Bangsar',
        address: 'Bangsar, Kuala Lumpur',
        state: 'Kuala Lumpur',
        price: 1200000,
        price_per_sqft: 600,
        bedrooms: 0,
        bathrooms: 2,
        size: '2,000 sqft',
        property_type: 'Commercial',
        tenure: 'Freehold',
        built_year: '2010',
        listed_date: '4 Dec 2024',
        furnishing: 'Unfurnished',
        description: 'Prime commercial space in bustling Bangsar area. Ideal for businesses looking for high visibility location.',
        facilities: { amenities: ['Parking'], common_facilities: ['Reception', 'Elevator'] },
        images: ['property4.jpg'],
        image_count: 1,
        main_image_url: null,
        latitude: 3.1319, // Bangsar
        longitude: 101.6741,
        source: 'mock',
        scraped_at: '2024-12-04T00:00:00Z',
        created_at: '2024-12-04',
        updated_at: '2024-12-04',
    },
    {
        id: '5',
        listing_id: 'mock-005',
        listing_url: 'https://www.propertyguru.com.my/property-listing/mock-005',
        agent_id: '2',
        property_name: 'Spacious Condo in Setia Alam',
        address: 'Setia Alam, Shah Alam',
        state: 'Selangor',
        price: 550000,
        price_per_sqft: 393,
        bedrooms: 3,
        bathrooms: 2,
        size: '1,400 sqft',
        property_type: 'Condo',
        tenure: 'Freehold',
        built_year: '2016',
        listed_date: '5 Dec 2024',
        furnishing: 'Partially Furnished',
        description: 'Family-friendly condominium with excellent facilities including swimming pool, gym, and playground.',
        facilities: { amenities: ['Swimming Pool', 'Gym', 'Playground'], common_facilities: ['Parking', 'Security'] },
        images: ['property5.jpg'],
        image_count: 1,
        main_image_url: null,
        latitude: 3.0996, // Setia Alam
        longitude: 101.4440,
        source: 'mock',
        scraped_at: '2024-12-05T00:00:00Z',
        created_at: '2024-12-05',
        updated_at: '2024-12-05',
    },
    {
        id: '6',
        listing_id: 'mock-006',
        listing_url: 'https://www.propertyguru.com.my/property-listing/mock-006',
        agent_id: '3',
        property_name: 'Bungalow in Tropicana Golf Resort',
        address: 'Tropicana, Petaling Jaya',
        state: 'Selangor',
        price: 5200000,
        price_per_sqft: 867,
        bedrooms: 6,
        bathrooms: 5,
        size: '6,000 sqft',
        property_type: 'Landed',
        tenure: 'Freehold',
        built_year: '2014',
        listed_date: '6 Dec 2024',
        furnishing: 'Fully Furnished',
        description: 'Exclusive bungalow in gated community with golf course views. Premium living at its finest.',
        facilities: { amenities: ['Private Pool', 'Garden', 'Parking'], common_facilities: ['Golf Course', 'Clubhouse', 'Security'] },
        images: ['property6.jpg'],
        image_count: 1,
        main_image_url: null,
        latitude: 3.1078, // Tropicana
        longitude: 101.6166,
        source: 'mock',
        scraped_at: '2024-12-06T00:00:00Z',
        created_at: '2024-12-06',
        updated_at: '2024-12-06',
    },
]

export const propertyTypes = ['Condo', 'Landed', 'Commercial', 'Apartment']
export const locations = [
    'KLCC, Kuala Lumpur',
    'Damansara Heights, Kuala Lumpur',
    'Mont Kiara, Kuala Lumpur',
    'Bangsar, Kuala Lumpur',
    'Setia Alam, Shah Alam',
    'Tropicana, Petaling Jaya',
    'Cyberjaya, Selangor',
    'Putrajaya',
]

export const getAgentById = (agentId: string): Agent | undefined => {
    return mockAgents.find(agent => agent.id === agentId)
}

export const getPropertyById = (propertyId: string): Property | undefined => {
    return mockProperties.find(property => property.id === propertyId)
}

export const getFeaturedProperties = (): Property[] => {
    return mockProperties.slice(0, 3)
}

export const getRecentProperties = (): Property[] => {
    return mockProperties.slice(0, 6)
}
